name: run

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup-layers
        run: ./setup-layers --destdir .

      - name: oe-init-build-env
        run: TEMPLATECONF=../meta-java-test/conf/templates/java-test . poky/oe-init-build-env
