on:
  push:
    branches: [ "master", "master-next" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: security_public

    steps:
      - name: install Yocto Project dependencies
        run: |
          sudo apt-get install -y build-essential chrpath cpio debianutils \
            diffstat file gawk gcc git iputils-ping libacl1 liblz4-tool \
            locales python3 python3-git python3-jinja2 python3-pexpect \
            python3-pip python3-subunit socat texinfo unzip wget xz-utils zstd

      - uses: actions/checkout@v4

      - name: setup-layers
        run: ./setup-layers --destdir .

      # see https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2056555
      - name: apparmor
        run: |
          sudo tee /etc/apparmor.d/bitbake > /dev/null <<'EOF'
          abi <abi/4.0>,
          include <tunables/global>
          profile bitbake /**/bitbake/bin/bitbake flags=(unconfined) {
                  userns,
          }
          EOF
          sudo apparmor_parser -r /etc/apparmor.d/bitbake

      - name: bitbake
        run: |
          TEMPLATECONF=../meta-java-test/conf/templates/java-test . poky/oe-init-build-env
          bitbake core-image-minimal
